# Generated by Django 5.1.5 on 2025-02-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation why this choice is correct/incorrect'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Whether this is the correct answer'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(help_text='The choice text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(help_text='Explanation shown after answering'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(help_text='Order of question within the mission'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='The question text'),
        ),
    ]
