# Generated by Django 4.2.19 on 2025-02-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
