# Generated by Django 5.1.6 on 2025-02-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Explanation of the correct answer'),
        ),
    ]
