# Generated by Django 5.1.5 on 2025-02-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_question_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='explanation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(),
        ),
    ]
