# Generated by Django 5.1.5 on 2025-02-07 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_choice_explanation_alter_choice_is_correct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeranswer',
            name='is_correct',
        ),
    ]
