# Generated by Django 5.1.6 on 2025-02-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_question_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='content',
            field=models.TextField(blank=True, help_text='Mission content/learning material'),
        ),
    ]
