# Generated by Django 5.1.5 on 2025-02-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_choice_explanation_alter_choice_is_correct_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={},
        ),
        migrations.RemoveField(
            model_name='mission',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='current_mission',
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='completed_missions',
            field=models.ManyToManyField(to='game.mission'),
        ),
    ]
