# Generated by Django 5.1.5 on 2025-02-11 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_load_initial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playeranswer',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='playeranswer',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='playeranswer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.playerprofile'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='current_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.mission'),
        ),
    ]
