# Generated by Django 5.1.5 on 2025-02-12 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_mission_options_remove_mission_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['order'], 'verbose_name': 'Mission', 'verbose_name_plural': 'Missions'},
        ),
    ]
