# Generated by Django 5.1.5 on 2025-02-12 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_mission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerprofile',
            options={'verbose_name': 'Player Profile', 'verbose_name_plural': 'Player Profiles'},
        ),
    ]
