# Generated by Django 5.1.5 on 2025-02-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_playerprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='mission',
            old_name='best_practices',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='mission',
            name='key_concepts',
        ),
    ]
