# Generated by Django 5.1.5 on 2025-02-12 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_update_mission_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['order'], 'verbose_name': 'Mission', 'verbose_name_plural': 'Missions'},
        ),
    ]
