# Generated by Django 5.1.5 on 2025-02-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_mission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerprofile',
            options={},
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='completed_missions',
            field=models.ManyToManyField(blank=True, to='game.mission'),
        ),
    ]
