# Generated by Django 5.1.5 on 2025-02-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_alter_playerprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='playerprofile',
            options={'ordering': ['-total_score']},
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='unique_question_order_per_mission',
        ),
        migrations.RemoveField(
            model_name='playeranswer',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='mission',
            name='best_practices',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='key_concepts',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='completed_missions',
            field=models.ManyToManyField(blank=True, related_name='completed_by', to='game.mission'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('mission', 'order')},
        ),
    ]
