# Generated by Django 5.1.5 on 2025-02-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_alter_mission_options_alter_playerprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprofile',
            name='current_mission_id',
            field=models.IntegerField(default=1),
        ),
    ]
